### ISSUE TITLE
Feature: User-can-view-agents-and-description

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project-v2#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
user will be able to view all agents with a description of the agent when they hover on it 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
user will be able to view all agents with a description of the agent when they hover on it 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/90476994/155813720-33cb04ec-3467-40cc-a23c-5b141c7d3698.PNG)
![Capture](https://user-images.githubusercontent.com/90476994/155813802-519d37bf-41e8-4dd1-8ad5-e3b16286b71f.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] add a background image to the body 
- [x] then we need to retrieve the data from the API
- [x] we create a div that has data-view='home-page'
- [x] inside the div create a ul 
- [x] loop over the agents and then create a li for each character and append it to the ul 
- [x] whenever a user hovers over the agent card the card will scale bigger 
- [x] whenever a user hovers over the agent card a text description will appear 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
