### ISSUE TITLE
Feature: User can view agent abilities 

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project-v2#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user will be able to view agents abilities
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

I plan on implementing functionality that allows users to view agents abilities with a description of what they do as well as a short gif showing the ability 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/90476994/156086541-33a8d95a-7a26-4a8a-b894-943ab8e91b3e.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a button to click that takes the user to the agent page 
- [x] update the view to equal to the agent page name 
- [x] add gifs of each ability for each agent 
- [x] add description of each ability 
- [x] make sure that the view stays the same when refreshing 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
