### ISSUE TITLE
User can favorite a character 

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project-v2#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can favorite a character and when they that character will be added to their favorite list 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
additionally, the user will be able to favorite a character when they favorite that character they will be able to go to 
a view favorite page which holds all their favorited characters in there 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/90476994/156875372-f49490a3-31c8-4254-9bae-d04ea2cc760d.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] first, we make a new div that holds data-view="favorite" 
- [x] then add the star icon to the img-container div 
- [x] in the js file add a function so that when a user click on the star it changes from an fal star to an fas star 
- [x] when someone click on the favorite icon push the img-container and all its children to the favorite array
- [x] when a user click again to unfavorite then reset the star back to an fal and remove the selected div from the array 
- [x] build the favorite page through the dom tree
- [x] make sure to update the domContentLoaded function so that when a user is on the favorite page and reload it doesn't go back to the home page 
- [x] add an anchor to the navbar of the page "favorite" 
- [x] add a function that switch view to the favorite page when a user click on the "favorite" anchor tag 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
