### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by moamel-hashim** [moamel-hashim/ajax-project-v2#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user will be able to delete a favorited character 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when a user click on the trash icon a model pups up asking the user if they wish to delete a character from a favorite 
and if they do the character won't be seen in the favorite array 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Capture](https://user-images.githubusercontent.com/90476994/159181599-386b7dc3-5f45-4a52-9cfc-bd0d11126e40.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] first, we need to add the trash icon to a favorite page 
- [x] then we give the trash icon an attribute of the character name 
- [x] then we need to match if the character name of the trash icon is equal to the name of the container then we show the model
- [x] inside the model the button cancel will hide everything back to the original state 
- [x] when a user click on the confirm button then the character will be deleted from the favorite array as well as the element container 
- [x] we need to match the trash icon display name with the container name and if it matches then we remove that container 
- [x] as well as we need to loop over the favorite array and check if the favorite array display name is equal to the trash icon character name if it is then we remove the object from the array 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
